### PR TITLE
Rename products to avoid collisions if used with swift-png

### PR DESCRIPTION
**Pull request by valeriyvan**
Solves #4

### CODE REVIEW

**Review by tayloraswift — APPROVED** [review]

**Comment by tayloraswift** [comment]
looks like CI product names were not updated

**Comment by valeriyvan** [comment]
> looks like CI product names were not updated

fixed

**Comment by tayloraswift** [comment]
the tests in https://github.com/kelvin13/jpeg/tree/master/utils also need to be updated:

https://github.com/kelvin13/jpeg/actions/runs/3043428379/jobs/4902682333#step:4:3063

**Comment by valeriyvan** [comment]
> the tests in https://github.com/kelvin13/jpeg/tree/master/utils also need to be updated:
> 
> https://github.com/kelvin13/jpeg/actions/runs/3043428379/jobs/4902682333#step:4:3063

Fixed. All tests succeed locally.

**Comment by tayloraswift** [comment]
ugh, it looks like testing scripts are using the product names to generate paths to the examples in https://github.com/kelvin13/jpeg/tree/master/examples

**Comment by valeriyvan** [comment]
> ugh, it looks like testing scripts are using the product names to generate paths to the examples in https://github.com/kelvin13/jpeg/tree/master/examples

checked all tests.
all work.

* `JPEG-unit-test` works fine in debug configuration but doesn't compile in release because of `@testable import JPEG`. Because it is not test target.

* `JPEG-comparator` crashes because of devision by 0, but it's not related to PR.

@tayloraswift Could you please review and merge. Then I could make PR for #12.

**Comment by adam-rocska** [comment]
it'd be great to have this fix. It's a real pain in the ass :(

**Comment by valeriyvan** [comment]
Both `swift-png` and `jpeg` packages could be used together if module aliasing is used for one of packages like in this [PR](https://github.com/valeriyvan/swift-geometrize/pull/116/files). So this PR is not needed anymore.

**Pull request closed without merging**
